service: apollo-web3-serverless

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, 'dev'}
  env-file: .env.${self:custom.stage}.json
  serverless-offline:
    noPrependStageInUrl: true
functions:
  graphql:
    handler: handler.serverHandler
    environment:
      WEB3_PROVIDER_URL: ${file(${self:custom.env-file}):web3.providerUrl}
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
